[package]
name = "borrow-check"
version = "0.1.0"
authors = ["Niko Matsakis <niko@alum.mit.edu>"]

[dev-dependencies]
assert_cli = "0.5.4"
diff = "0.1.11"

[dependencies]
abomonation = "0.5.0"
abomonation_derive = "0.3.0"
differential-dataflow = "0.5.0"
failure = "0.1.1"
timely = "0.5.1"
fxhash = "0.2.1"
itertools = "0.7.8"
petgraph = "0.4.12"
structopt = "0.2.8"
clap = "2.31.2"
histo = "0.1.0"
relation = { path = "relation" }
